import jwt
import uuid
import sys
import os
import datetime

# ==========================================
# PUBLIC KEY
# Replace the value below with the exact contents of your public_key.pem
# generated by OpenSSL.
# ==========================================
PUBLIC_KEY = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3PBCYtJ6BeKqz9qpJqR5
aCDYeNQiKUcjAhaHhcJQpP4yFNRSbnvNw1+tm+NgNkkjMNPv2LQbbi4eDcIoz8WQ
+kr1dfH5Cu81bdD0exbD+1M6akXjTdiQI58vLLNchNNM4M3bhO4GDQTja2c3Z0o/
etHn0a5xebNNm4YAoBmz4P/AbkFthYXtUFt/VjC7Euzv1onEIQ1ZnsE9zEwstd3F
hMFuEt2yT7upujNUbHkakJu9TsKQSCRS1601ha95Qte3ZMzZHF1w7xDLLLVa1bZk
HQo5NTa/CRBbAMkzJauPezCGGssbrtComHLydQ0JXzQ6uiQ4kauTxDkITLA5t/lh
EQIDAQAB
-----END PUBLIC KEY-----"""

LICENSE_FILE = "license.key"
LOCK_FILE = "hwid.lock"

def get_hardware_id():
    """Generates a unique hardware identifier based on the server's MAC address."""
    mac_num = hex(uuid.getnode()).replace('0x', '').upper()
    return f"HWID-{mac_num}"

def verify_and_load_license():
    """
    Reads the RS256 token, verifies its cryptographic signature,
    enforces hardware binding, and returns the licence payload.
    """
    print("==========================================")
    print(" LICENCE VERIFICATION")
    print("==========================================")

    if not os.path.exists(LICENSE_FILE):
        print("CRITICAL: 'license.key' file not found.")
        print("Please run the installer or place a valid license.key in the application directory.")
        sys.exit(1)

    with open(LICENSE_FILE, "r") as f:
        token = f.read().strip()

    try:
        # Verify the token signature and expiry (raises on failure)
        decoded_data = jwt.decode(token, PUBLIC_KEY, algorithms=["RS256"])

        client_name = decoded_data.get("client_name", "Unknown")
        tier = decoded_data.get("tier", "Basic")
        jwt_hwid = decoded_data.get("hardware_id", "UNBOUND")
        expiry_ts = decoded_data.get("exp", 0)

        current_hwid = get_hardware_id()

        # Hardware binding logic
        if jwt_hwid == "UNBOUND":
            # First run: bind this key to the current machine
            if not os.path.exists(LOCK_FILE):
                with open(LOCK_FILE, "w") as f:
                    f.write(current_hwid)
            else:
                with open(LOCK_FILE, "r") as f:
                    locked_hwid = f.read().strip()
                if locked_hwid != current_hwid:
                    print(f"CRITICAL: Hardware mismatch. This licence is bound to {locked_hwid}.")
                    print("This licence cannot be transferred to a different server.")
                    sys.exit(1)
        else:
            # Key is explicitly bound to a hardware ID from the keygen
            if jwt_hwid != current_hwid:
                print(f"CRITICAL: Hardware mismatch. This key is cryptographically bound to {jwt_hwid}.")
                sys.exit(1)

        # Licence is valid — print summary
        expiry_date = datetime.datetime.fromtimestamp(expiry_ts).strftime('%Y-%m-%d %H:%M:%S')
        print(f"Licence valid.")
        print(f"Client : {client_name}")
        print(f"Tier   : {tier}")
        print(f"Expiry : {expiry_date}")
        print("==========================================\n")

        return decoded_data

    except jwt.ExpiredSignatureError:
        print("CRITICAL: Your licence has expired.")
        print("Please contact your provider to renew your subscription.")
        sys.exit(1)

    except jwt.InvalidTokenError:
        print("CRITICAL: Invalid or corrupted licence key.")
        print("Please ensure you copied the entire RS256 token correctly.")
        sys.exit(1)

    except Exception as e:
        print(f"CRITICAL: Unexpected licence error: {str(e)}")
        sys.exit(1)

# Global variable holding the active licence payload for other modules to import
ACTIVE_LICENSE = None

def init_license():
    """Initialises and validates the licence. Must be called before the bot starts."""
    global ACTIVE_LICENSE
    ACTIVE_LICENSE = verify_and_load_license()